language: java
# Trusty Beta requires sudo per https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

# Manually install cassandra until https://github.com/travis-ci/travis-ci/issues/3952
# See https://github.com/openzipkin/zipkin/issues/706
before_install:
  - curl -SL http://downloads.datastax.com/community/dsc-cassandra-2.2.3-bin.tar.gz | tar xz
  - dsc-cassandra-*/bin/cassandra > /dev/null

matrix:
  include:
    - jdk: "oraclejdk8"
      env: GRADLE_OPTS="-Dorg.gradle.daemon=false -Xms2G -Xmx2G -Xss512k -XX:MetaspaceSize=256m"
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/2.9
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/modules-2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false

env:
  global:
  - secure: EqDC/6Y7fNxP0DkmFsuaAmzrQNlsl1e4H77ySy4/BzZR9WGvuQYaAbPbx1H+wMYyzx+xZt5RECdwHcp2x8yE1/xmiSzSM+n1tVSRFUKdwmYZI81UZ0aJ7AnjLr/seJrvCqsaEeuLaJr7jKhyTFd8gmFC9xmp4q/Jn35EQLGP9+DmKlSL2joRxBYghoI14/bymMH6iuZGy/goWstU5TyHpTdzy7nZ9rO5aCtibDFffVn33z9c97QbG65kL5ft3qXS5kULvilW714PjMP7LvkHCqAb2Bb3MgEAq0Dk0pa/n8YqnOSlVq14TYi29dtonE/MXdhFh4t3ojbP9dL3At/yQ/NEBTvseiaUNEtrZBsTpLmG2P2zhNvoBCt6CSJkC1hklxsePcFgbLVLWeQz6AhFZapYFvoaWsnfeRiuXakq9+kHTStNJiSg/xuVyEo1XB2W5nCTByt9WxPKwtMJari8u2QkXDu4M6XYFnuSxDonR+7tfb1Sqsd1OdGnji6dnKzd9OirlwEDF0VOyYI3genAZmFkKl1d6uBWg7Be0Asv3Pzr25Ka9UEoCB5WpIjxTTOM+QHW1HNfCYc8mNTxoP+cH4baRgsIpd/YPk4VAW+Uk2ph0odYkQu8HeJjsoEB646X8ZhCaoMF8KEFWmRzNH8IFDRfBWBuRMTU5PQv2XFEQIU=
  - secure: HavRoQUk9Gzg6g9xt3Pl4sezZoUah90V/w09lTlsArrj+7GDqK4ak/zNwBC5MPzgkST+/ABPrmX3m6NzD6NK5DxdpiTrtQVlUiteFOFSKr9R6z0hnBHtu+CNqqLmpMusG3C1ThYO5ZdMHmvSTkC6E51AljditoxkiYnDV2TOyUrgIsWZ3JJMHSg7lMHomAlXZMx2vELCx7WNSQVVEY+ozPw0W5gEANrsK+XZnY2sRBRVmogGhpdqBIhuFqyNwaWs/VW4sMVStPbGNpfZ3HtFMQlpgfKLVaqAy1s4ylgIBoUSD0O5h4wSaLJmZ0e5KxJKfaiVfVKIH2plFfvu+52Ic/HyVrgzWRwM9Fdf5rQOnqn9pbmX/Hwgiw31LOPV2jVx+ratQm4MU/2RhhaHVxRWm6w+p0/N+QmrSBD46j81nV9y+4vWdMmpKV7XRkbv6x2szNp7sXDCpY/tAb5xSyOvrPzdkEFSCcguC0U0Oo0SrwFQyhZaOZNiy08Nqc+a/PkxHIB2Iy2isN/1CoKAViwlcHWrmxGZX0xtf2LGp55n1QiUydj56bOzuxBTxjXpCcJQq13BSQTb+Qhvp7Bn3xCYDxfdp1UzgRWm8KDTvWaHUIAbJBp4hRhpWMNpgvUWjGS2SjRxhV7SEw7O0qUDQOK1guzSQ81LQGcLJ5UFT8TWZEw=
  - secure: cR/lmFlQyLzPd6BOMlWJdicNuDY/+ah0WTJ52rTs/TLnw8lEswlTX/lmg34dxLBRjbI4WNMQdch3DK8grgUUl4wvtOJ/aWZBnxMY/4JdW6qgOJIV6Bqlmi5Rvr/Kt7AfwyWURP/Ac4zULAdq2NNUJL6X0FqyMpH1ieXTWhfdnTKsfBnhRNzWA6PVqvP1jkYt8F0ewoM8hXq/otH8M3H/q5KivK5WSWMpe9T544aLua/OkSmGBu/9k1F1nMsQs2XjsHfasfn5iGkM6OD9b2mOILSP8jqs6aXsoqq7+3ousAq7+SXLA7uj2kRJfofiKwggt4ScHq1TAX2aWGstxAUQ2QCPp6vtnbsBRDycyFKjv9Vq0CtDP1dQ4kzAo4TD5lvGE+JwVLBGtnq3YJdO0r25K6+Suwtu53hdqUrOnbIU/RGG4YOrWH8fpii5UfHx9iW67kTPOIO8SjbW8t+49b6UNjAk1h/K8NNTA9vNxjPRvP7+QWwIV9fBlCX3dlE7xapShLZx1wvB35trVStUhf23DFxABY/W8NIpy3iRs+6aj4ocZ+kPw32eYI/xaLA1U9eWE5aq8dRvxgP7wBud94a0LE/0DD2XGAlIZ4Oe/kk440L/u0M2UNhIwSTGZgQsoiaJYIGc+D7qSwA2Emmx5zkcGMzrN6qbPk92b9Ed0e67r1Y=
  - secure: YBuP0dulj0DV7qi5iP4Gwu+MzsVjsNleW4WOrNNTdgDeG+Jx2SGfA8kSCqkOXa9XgIALwcfSdBwA1x3HrVpD3XxjbduzY4YNAmuu4eTx8U7BVdYERwogAC1PUZ6y5b+Wa/4XQ9FpviAEfZhaOqIxQAWsGsyHo3qNSzAFqSCJpPbDfcHLJ53lICQ3SGA5ise0pRRrJMNcDyzzKs4RZlr+NqKctyFklkn5cvMV7PsF/AAKgrzid6FkIwJeljFppPLeI16MIzqdxU0L5NORZUalHXaf8O8NHg/AAprbISCvRWGwBL2u7Mm51UxFEsgesL8PSoirwjsZRGnD8mLocUi6+roDMiZY+s/7mmZ5J3LifeNCd0aL64OopalYbY8wbDGm3mvCfAVdXeZfKNMYVCG4mB8VyIV4dxL7mhOYrGRqwHWcxFvxgdjsxy1ZU77BoIM15MlobASynuZCLjK0PUn1hxn7V9ISZindFjXRsXQkdZldU64gpC7K/OBrXeAkEZjfgGhR1yivdLa6qM7Ax+HdQPeAeDyc5jh3cKAaRSvNC2y30W6rzIznxB+I8H8Ey7CmwpZjUKiqTEsLaijwutKSDi9MX2iWDDUx/Y8YmgNMcQmny+YhAgmEO3XOYLFgH20x4te1EG1Gaj8Xg0xYrV2R1iXMqdSnG6V04wQem0Mtu9I=
  - secure: zVvHPQ7srHwjzyN7Y+vZoa22NQ9tgl2vgX+/pwxT6HGzj2leJL/mJN4AqbVqZnpLiwvRJH//e5bcsyq7defbE/hJ6+jmvbtvd6ry6OmY54Oqt672plaEBizEYzCUsdRGkOPXaV8HFm8mAMbSFwVYce1opxJnPQJXvJFfG4cKMXPYllYmupE6EjwOIsE6TETbGqiX/cXyiSz+Dc7ieTti+MBPeISFau7N29ZKZGUOUsN1sCIgLJy/w5IDFxA1eGBFHvG4vraYR04/cBgBnmATu1UB4TEXmhZKinmbOkEBHJby5wxXDgHF7JAOheyoQgdfsdkUuww3KeEnhjCl3T4t2I3m00sl6nfo9phv+Y8IzwTq1kJVj1/XtLZJDXydFBXOL/QhCKPX6yhO4ZyNXup/yN+4dwhfcrJ6lP4YKK89DwH6N2Tuvea4If7/GU/lf+VTgbrnO5hW/PWK+zJomgHMQIR+Q6sr6GqSESk7ywNqkLDXnQMt0b33YisvZYtIM7qDJKViAQS0P8NLpsu1
f244DnmKq+RBnrjxX4FNcAmBQK0OiGdHvNETgofzDNfEAAxTUNXmCU2rmJypJ0qtQUAdhqoHNI6qHdMcKce8FCLO6lBevnQOEsKxVwG76DVfbtbBBIRAmy5zNasOCTuUDW2+iTVNIiR3skx+3qc+9bwmknw= 
before_install:
  - git config --global user.email "${GH_USER_EMAIL}"
  - git config --global user.name "${GH_USER}"

# Skip `./gradlew assemble`
install: /bin/true

before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"

script:
  - ./travis/publish.sh
