language: java
# Trusty Beta requires sudo per https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

# Manually install cassandra until https://github.com/travis-ci/travis-ci/issues/3952
# See https://github.com/openzipkin/zipkin/issues/706
before_install:
  - curl -SL http://downloads.datastax.com/community/dsc-cassandra-2.2.3-bin.tar.gz | tar xz
  - dsc-cassandra-*/bin/cassandra > /dev/null
  - git config --global user.email "${GH_USER_EMAIL}"
  - git config --global user.name "${GH_USER}"

# Skip `./gradlew assemble`
install: /bin/true

before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"

script:
  - ./travis/publish.sh

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/2.9
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/modules-2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always

env:
  global:
  - GRADLE_OPTS="-Dorg.gradle.daemon=false -Xms2G -Xmx2G -Xss512k -XX:MetaspaceSize=256m"
  - secure: "DKHylOWwwIrRudcfXjmkVGg7gjfY5UWRE4wT+qAYRX9vaf8lGNoCTw67jaD41An8DEVogxsOIRwPXqFlKwQBZUgRCUFr2DLvOu77UV3Uo/O09FZaWBdOhlUWOmwX1UAvrV9UfLPD5L7lsa5v6k6dmrZ/G1b0bI8bJcUkDNBYZrHsdLACBJrA9iA7ofCM9IeXBhvxPYH4B0An4LYaOMbs990yU1QOTfKxcHzM9bcQP8KeZZoXbKeQvP0IZ8JyjscKN6AJ+TxJBPB8I5l9Lpva6mqDhx7hCnpsO6d0eaZPnADo2VEqcEO28X7i0v1comi3v7d+48JAelH05KSw0bGICh+30QbnAFYLWF2oMGUe3xI2p4+hdpj63jTOcpyBAHIUlzAk6R85SOq4aLVCAwUhNMqaj4aqYlNEFisJJmi2IZ90vD54rxImEQhGf0A9b3CutL/ULD5DFqFJExQFbM8Vz6FqhUcfoZTMMJCb8GIPi9n3X8QYhlKP5Ui6Y4cQmIfN6Z8mjbBDsgbtNpJ1ZTG/HhQbFFOzITvLpXAxgGAJHhVZO3cakZZC6EehP8qswOkk1p7aMVcpbYRg7AbVt1dCqcwW2xB8CGoGxKl6rUAQ2KJ1hIbgtCsGMLZmYkWuWpFy07xA0YHvrMVvbcuZZF0jfpEkHOgKa0NvZ+9mYFqyGm4="
  - secure: "WrxDas9TyIZi1rhjWQHxNzsmUF9XYwMdaYfGPcpwtKzIQt55GIh6whTuIbkwt2MO4E8wgMby0HsnuuDZPhcDK1s8PwPpamfnfibE7Qm7XkKwqHgpYKRh3piwV/vsLtLaV3OAHWPwhxpD0nfeVq++DcvlcD/c9+kzZfHc+yXAd2+HpAdMxPJM5Vp7ie6mEk02srvk7TEzqv0vgKpcXBd88/0ZxRN3viGoQ4IkykHn8E4bOW7ybPyZkRINYCJ0zs6YBM6KR+OT5c7k2wljysUEfP4H9HQxA/kkko19UJuNVK4U7C4Gb3zKphXPMCbqQbXtGuiZLl4ViMPDAX1u9KochiiQQwHUj+J0E2FqYJDNzN21Qc+hbc0z8AqlKvpKGUCPuOLFhneCXvn/ui5LA8eM9tXaQM5Zqkrr2cc4YhcyGTmgjTKwX3LzdFtn2agPXM0ZLt3MoWBq1M9ekGEQMQR7higm1chaGVDNfDbjNeYiA055ibTGY3XaVN+3h/SDvBenBFvFwVpz3A5FQMtid/Z6RMxyXA0SH5JfiLVcQ3Pn/7uO8TjU/wXcx0YWHt79eK/XZzSTZe1bdb00Kptr+GP7E1+tm5lAFehQEBSaC3akLsq3E9mSfo/SsN3JjoDzfMO8CbQkKIFxPIa4e4/wBH7FW3LVpEtWR8n49XEvLI1nTEs="
  - secure: "rrupP7POyqL1azPH7DyAKmA7DyAj4x5lVnFrCd1GmChqYV4HMiOWQ37hiO2kCmVikZTZ9EOg/1iMv8YiRtBimBMUzPxbbLaGJkF7IXb3byGGJ3zVh5AdAs9VXGxRYrAnrFRISc8RX0ULjeLeUlB+TUm2yaYVreCxZ9P9jUYnMhaXiniwXUCPDvdTOtRILUSxpr7pYbh3EviWhKSrsrce8AJwLR6EZ+7/DW2cGDajdiqG1nBhqiBeHez2/XyoLMbHKS7PFZJ3NrFmMI0JGdMyjxdVV8Fc+OlclqpR0FB4lvGxTL0Ov7TdzznqkxGb1qIg06gHpMXQEh3+qKvSrdq0LsPqtUdm2KQZCts0SxApHZbMWIRt2ap/B8yQq6ZkUpkJoHoSltX0OfEI5pqhZ1aNXqlvjGgAxlvotjs0XaWrGsnhOQwhc6Aro8gMcnEI8JzMyYBa1ZKwz+zrYW869Eq/w6Fp8uE7g4+peCKQs65X8NJBUtYTRvTDjdjly49VMT4ETuym/3UyvzxnV+KoAg5mD8MzlX49zEdMAmqkt3rr9OPDspHW7fycilwEM6ee66q+zUejyH3Xo6oIfqC5Pniu+ADXcwm4UDDYsYhN8dXXqiXs2YZqKGNWNtryRVwIZclVjRU9EbJ9+hR9Gq/hFh0n2Nn7zzWbeCiHX3loh14OgCs="
  - secure: "rEtoL7Nf1wiGt8ebj4Wc4do5fXjanDkb8DrIeXoQAsmG/H4GlvXuuxh4PyIJvJzysemNEIqqeDVLfCr+WL99fctBHHTRMoCj4cDv25TIMmQAO2yE8KjhDSWzC07sJqnwrO/z+lYIpoGB1BoYd5XL1R0u5D6A40o8lYLTT4byNDpMiSpl8cj3YBe2OIfZte03PvhwIySWO+Fm0hoJXNnhudoaZT5Hir1itCb776HCDDGOQyAc5QYxv+iOkJ0wlsV0vHD/TEzz6yse6V1n83JLXDxwxwZvHuU11up1++UYa9pTwmIDRU7a2YjDoRU35ksTaiQIs6DPxr9v1IJLQA+8dT9V+yBFTncLrEwo5UY8iwr6T2ZJw3vfpXB2zR/Q3gU2rK2wXn74u+OpURRfi91TKh7B/1XsE3EmpCYEIss1izxVPhDJWfwjVMTFNQs6G4MFVgz3k57MU+wLjR9aajlvO24RRi2g925mC7qqzLbW3/gRE6WllNKH+XUYqX8K7x8QkXwFaQi4ZHJSEOi2A+JFDLN7RmnrGrGknTXc+e62Foz3KTAhJgu9TPpdjs1L7FZzPQlfEjBNGEpll4ViT7JEc9+47SK24JYv/tM79guwKVsMP9EV7Pe+qzjMO5/AAX3W5GnM5KGt2oklXgGMZzbNfnEoG3vfW0vJAql6F8/3PHo="
  - secure: "rEPznuuKT5E3Eb4hOCYQ0sRQQXxTZSMnd1RBHJQYuEC04qoRe2dUghmq5Z33t+IelZCFcKg6xvWkwKOJUQKo5oZGmDX0LxNw4OKRwyYDBDmP/OKNHr8od+LQg7uh1Yze179ZqK73UbICxHg3mTGLmgG5kWE+f5RMLmuSQ4FxvJxtwHbcFYaHV6SWRfWaz2QNcmh1j4yjXBFbyKo7j1uGLhXzG0v6QZR2Rs2pRIcw5gzr9QvngeTC3QKYTl4r+pQhMeX93FHD7rdXFUruQfnjU15E6K4+AOIEnbgJhsCgvoE89JCYHWAF4hugFeOM/hTqkwsiLHCFAik+Gn9lpaiqytmwtQywvq6yKo+MVz4i3ViAt4KAjXOGMVkNmHyN2vE1nbI5TQJK0k0nGMhv5WsWQuyslhRhvxvhNFFdfQwNLGnLxCgO9WD9eglwI0za8+u73DVmuzEhI8SIbJ0fpjEkHvAYLe5wyN3U7FjL9AFF9x18tIm5smTv4r41QIU4H4YRozqOWu9D2GfdEd8KVJE16HsSGa0rKJiVDPOJVc6Qe9OKv2QafpIUDQXMCjacPi/JJ/J76OZyMEJA3ErC/HjkAWNkq78MJijLg7VoZGc/OLIssJwa/r93DK6mekd9z/5TkIMIstaRWaDAkCzZgeCkHvk8Q0YVWMQr/V3VAIsq1MQ="
