language: java
# Trusty Beta requires sudo per https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

# Manually install cassandra until https://github.com/travis-ci/travis-ci/issues/3952
# See https://github.com/openzipkin/zipkin/issues/706
before_install:
  - curl -SL http://downloads.datastax.com/community/dsc-cassandra-2.2.3-bin.tar.gz | tar xz
  - dsc-cassandra-*/bin/cassandra > /dev/null

matrix:
  include:
    - jdk: "oraclejdk8"
      env: GRADLE_OPTS="-Dorg.gradle.daemon=false -Xms2G -Xmx2G -Xss512k -XX:MetaspaceSize=256m"

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.9
    - $HOME/.gradle/caches/modules-2
