language: java
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer

matrix:
  include:
    - jdk: "oraclejdk8"
      env: GRADLE_OPTS="-Dorg.gradle.daemon=false -Xms2G -Xmx2G -Xss512k -XX:MetaspaceSize=256m"

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.6
