# Default JDK is really old: 1.8.0_31; Trusty's is less old: 1.8.0_51
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

before_install:
  # Manually install cassandra until https://github.com/travis-ci/travis-ci/issues/3952
  # See https://github.com/openzipkin/zipkin/issues/706
  - curl -SL http://downloads.datastax.com/community/dsc-cassandra-2.2.7-bin.tar.gz | tar xz
  - dsc-cassandra-*/bin/cassandra > /dev/null
  # Manually install elasticsearch until https://github.com/travis-ci/apt-source-whitelist/issues/190
  - curl -SL https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.3/elasticsearch-2.3.3.tar.gz | tar xz
  - elasticsearch-*/bin/elasticsearch -d > /dev/null
  # parameters used during a release
  - git config --global user.email "${GH_USER_EMAIL}"
  - git config --global user.name "${GH_USER}"
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install:
  # Override default travis to use the maven wrapper
  - ./mvnw -q install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always

env:
  global:
  - GRADLE_OPTS="-Dorg.gradle.daemon=false -Xms2G -Xmx2G -Xss512k -XX:MetaspaceSize=256m"
  - secure: "DKHylOWwwIrRudcfXjmkVGg7gjfY5UWRE4wT+qAYRX9vaf8lGNoCTw67jaD41An8DEVogxsOIRwPXqFlKwQBZUgRCUFr2DLvOu77UV3Uo/O09FZaWBdOhlUWOmwX1UAvrV9UfLPD5L7lsa5v6k6dmrZ/G1b0bI8bJcUkDNBYZrHsdLACBJrA9iA7ofCM9IeXBhvxPYH4B0An4LYaOMbs990yU1QOTfKxcHzM9bcQP8KeZZoXbKeQvP0IZ8JyjscKN6AJ+TxJBPB8I5l9Lpva6mqDhx7hCnpsO6d0eaZPnADo2VEqcEO28X7i0v1comi3v7d+48JAelH05KSw0bGICh+30QbnAFYLWF2oMGUe3xI2p4+hdpj63jTOcpyBAHIUlzAk6R85SOq4aLVCAwUhNMqaj4aqYlNEFisJJmi2IZ90vD54rxImEQhGf0A9b3CutL/ULD5DFqFJExQFbM8Vz6FqhUcfoZTMMJCb8GIPi9n3X8QYhlKP5Ui6Y4cQmIfN6Z8mjbBDsgbtNpJ1ZTG/HhQbFFOzITvLpXAxgGAJHhVZO3cakZZC6EehP8qswOkk1p7aMVcpbYRg7AbVt1dCqcwW2xB8CGoGxKl6rUAQ2KJ1hIbgtCsGMLZmYkWuWpFy07xA0YHvrMVvbcuZZF0jfpEkHOgKa0NvZ+9mYFqyGm4="
  - secure: "WrxDas9TyIZi1rhjWQHxNzsmUF9XYwMdaYfGPcpwtKzIQt55GIh6whTuIbkwt2MO4E8wgMby0HsnuuDZPhcDK1s8PwPpamfnfibE7Qm7XkKwqHgpYKRh3piwV/vsLtLaV3OAHWPwhxpD0nfeVq++DcvlcD/c9+kzZfHc+yXAd2+HpAdMxPJM5Vp7ie6mEk02srvk7TEzqv0vgKpcXBd88/0ZxRN3viGoQ4IkykHn8E4bOW7ybPyZkRINYCJ0zs6YBM6KR+OT5c7k2wljysUEfP4H9HQxA/kkko19UJuNVK4U7C4Gb3zKphXPMCbqQbXtGuiZLl4ViMPDAX1u9KochiiQQwHUj+J0E2FqYJDNzN21Qc+hbc0z8AqlKvpKGUCPuOLFhneCXvn/ui5LA8eM9tXaQM5Zqkrr2cc4YhcyGTmgjTKwX3LzdFtn2agPXM0ZLt3MoWBq1M9ekGEQMQR7higm1chaGVDNfDbjNeYiA055ibTGY3XaVN+3h/SDvBenBFvFwVpz3A5FQMtid/Z6RMxyXA0SH5JfiLVcQ3Pn/7uO8TjU/wXcx0YWHt79eK/XZzSTZe1bdb00Kptr+GP7E1+tm5lAFehQEBSaC3akLsq3E9mSfo/SsN3JjoDzfMO8CbQkKIFxPIa4e4/wBH7FW3LVpEtWR8n49XEvLI1nTEs="
  - secure: "rrupP7POyqL1azPH7DyAKmA7DyAj4x5lVnFrCd1GmChqYV4HMiOWQ37hiO2kCmVikZTZ9EOg/1iMv8YiRtBimBMUzPxbbLaGJkF7IXb3byGGJ3zVh5AdAs9VXGxRYrAnrFRISc8RX0ULjeLeUlB+TUm2yaYVreCxZ9P9jUYnMhaXiniwXUCPDvdTOtRILUSxpr7pYbh3EviWhKSrsrce8AJwLR6EZ+7/DW2cGDajdiqG1nBhqiBeHez2/XyoLMbHKS7PFZJ3NrFmMI0JGdMyjxdVV8Fc+OlclqpR0FB4lvGxTL0Ov7TdzznqkxGb1qIg06gHpMXQEh3+qKvSrdq0LsPqtUdm2KQZCts0SxApHZbMWIRt2ap/B8yQq6ZkUpkJoHoSltX0OfEI5pqhZ1aNXqlvjGgAxlvotjs0XaWrGsnhOQwhc6Aro8gMcnEI8JzMyYBa1ZKwz+zrYW869Eq/w6Fp8uE7g4+peCKQs65X8NJBUtYTRvTDjdjly49VMT4ETuym/3UyvzxnV+KoAg5mD8MzlX49zEdMAmqkt3rr9OPDspHW7fycilwEM6ee66q+zUejyH3Xo6oIfqC5Pniu+ADXcwm4UDDYsYhN8dXXqiXs2YZqKGNWNtryRVwIZclVjRU9EbJ9+hR9Gq/hFh0n2Nn7zzWbeCiHX3loh14OgCs="
  - secure: "rEtoL7Nf1wiGt8ebj4Wc4do5fXjanDkb8DrIeXoQAsmG/H4GlvXuuxh4PyIJvJzysemNEIqqeDVLfCr+WL99fctBHHTRMoCj4cDv25TIMmQAO2yE8KjhDSWzC07sJqnwrO/z+lYIpoGB1BoYd5XL1R0u5D6A40o8lYLTT4byNDpMiSpl8cj3YBe2OIfZte03PvhwIySWO+Fm0hoJXNnhudoaZT5Hir1itCb776HCDDGOQyAc5QYxv+iOkJ0wlsV0vHD/TEzz6yse6V1n83JLXDxwxwZvHuU11up1++UYa9pTwmIDRU7a2YjDoRU35ksTaiQIs6DPxr9v1IJLQA+8dT9V+yBFTncLrEwo5UY8iwr6T2ZJw3vfpXB2zR/Q3gU2rK2wXn74u+OpURRfi91TKh7B/1XsE3EmpCYEIss1izxVPhDJWfwjVMTFNQs6G4MFVgz3k57MU+wLjR9aajlvO24RRi2g925mC7qqzLbW3/gRE6WllNKH+XUYqX8K7x8QkXwFaQi4ZHJSEOi2A+JFDLN7RmnrGrGknTXc+e62Foz3KTAhJgu9TPpdjs1L7FZzPQlfEjBNGEpll4ViT7JEc9+47SK24JYv/tM79guwKVsMP9EV7Pe+qzjMO5/AAX3W5GnM5KGt2oklXgGMZzbNfnEoG3vfW0vJAql6F8/3PHo="
  - secure: "PqCWqR+uZGNSNmeByfFbPx9xAJ3OS1LbzriZAuzkDY27GSwp3e2omj0w7BILqjaFhgFT+EIPMvr0erUW3YumjJcivUInHkH2OKsnIeExD1OvdwaQk7lsr1mg7+X/fCiCr+MIdvXGalk7fb8W0BhwEaazGpYCjpZmuLFiqM8lZ70uJwztCCjJoEr29uykYlNsZ/BVHK7R8kRBsZAzBq5jCkcwJzpCg1Rql+JSC1gZUhbzb39GKvn0PAS2qVNbTRlqQrHZfS+kdaNLGZ+AE4dwaGmxLOJvMUURaOiIOgrUJAS4vKnuO242tpF+od7S2osgTfWm2DX0nc6/Y4VpcAHqjOqARvFwDXRwQwKtustlMngPCNVMVDN6fzXQ4g9RDyqHHeHuyWzKtQkeVrPZM8MUDmrIg9SD2jlKxcTCkZF9J3ZFc9r4fGuB6YRgezYI4WZnnPur/WgiDw6pSBX7qE3tMb1uR/ZzehsZo+c6h6oN64YGLlfPDcDlNMX0PtjRitGRA4s+Z1CAZVUDQ/IyrzhEEXVcBecqHwS4TYNTlJTygHZaMSOaZPqMBZprGFBqh9KM5OhkK1P75XSKQJxCUpk6mbOSxwcGku8ix7pVdYKX2fy8k/E7PKW/uKxzkFp0O3ejvDamO+2Rq88xZICLMrfudCLrzFwD8Y/ZxmSZqlogrgI="
